<style>/*Table Style */#tabletip {    border-collapse: collapse;    font-family: Helvetica Neue,Helvetica,sans-serif;    margin: 0px;	font-size: 11px;    text-align: left;	width: 100%;}#tabletip th{	color: #003399;    font-size: 13px;    font-weight: normal;}#tabletip tbody tr{	border-top: 1px solid #ccc;}#tabletip thead{	//border-top: 1px solid aliceblue;}#tabletip thead th{    //background: #B9C9FE;}#tabletip tbody td.b-left{	padding-left: 5px;	width: 20%;}#tabletip thead th.t-left{    //background: url("left.png") no-repeat scroll left -1px #B9C9FE;	padding-left: 5px;}#tabletip thead th.t-right{    //background: url("right.png") no-repeat scroll right -1px #B9C9FE;	}#tabletip td{	//padding: 5px;	text-shadow: -1px 0px 3px white;	background: -webkit-linear-gradient(top, #FAFAFA 0%,#F7F7F7 56%,#EDEDED 100%);	background: -o-linear-gradient(top, #FAFAFA 0%,#F7F7F7 56%,#EDEDED 100%);	background: -ms-linear-gradient(top, #FAFAFA 0%,#F7F7F7 56%,#EDEDED 100%);	background: -moz-linear-gradient(top, #FAFAFA 0%, #F7F7F7 56%, #EDEDED 100%);	background: linear-gradient(top, #FAFAFA 0%,#F7F7F7 56%,#EDEDED 100%);	-webkit-box-shadow: 1px 1px 0px 0px #545048;	color: #669;}#tabletip tfoot td{	font-size: 9px;	}	</style><?php/////////////////////////////////////////////////////////////////////////////////////// xbtit - Bittorrent tracker/frontend//// Copyright (C) 2012  !! Just Joking! No copuright. ;-D////    This file was Created by Bhorer_Alo//////////////////////////////////////////////////////////////////////////////////////        require_once ("include/functions.php");        require_once ("include/config.php");include ("include/offset.php");global $CURUSER;        if (!$CURUSER || $CURUSER["view_torrents"]=="no"){    err_msg('Error! You are not authorized to view this');    stdfoot();    exit();}
	function comment($hash)
		{
			include("include/settings.php");			$con = mysql_connect($dbhost,$dbuser,$dbpass);			if (!$con)			  {			  die('Could not connect: ' . mysql_error());			  }			mysql_select_db($database, $con);			//getConnection ()			//global $TABLE_PREFIX;			$commsql = mysql_query("SELECT user, TEXT, added FROM  `{$TABLE_PREFIX}comments` WHERE info_hash =  '" . $hash . "' ORDER BY added DESC LIMIT 0 , 5");						if (!$commsql || count($commsql)==0) 				echo 'No comments on this torrent.';			else {				echo   "<table id='tabletip'>						<tfoot>							<tr>								<td class='rounded-foot-left' colspan='2'>								<center><em>Comments Posted by Users</em></center>								</td>							</tr>						</tfoot>						<tbody>";				while($row = mysql_fetch_array($commsql))				  {						$str = $row['TEXT'];						$max = 50;						if(strlen($str) > $max) {						$str = substr($str, 0, $max) . '......' . substr($str, -10);						}				  echo "<tr>";				  echo "<td class='b-left'><b>" . $row['user'] . "</b><br/><small>".$row['added']."</small></td>";				  echo "<td>" . $str . "</td>";				  echo "</tr>";				  }				echo "</tbody></table>";			}
		}
	$hash= $_GET["data_hash"];
	if($hash)
		{
		comment($hash);
		}
?>